package faktura.USD.PLN.model;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import javax.xml.bind.annotation.*;
import java.util.List;
import java.util.UUID;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "invoices")
@XmlRootElement(name = "faktura")
@XmlAccessorType(XmlAccessType.FIELD)
public class Invoice {

    @Id
    @GeneratedValue
    @ApiModelProperty(value = "ID generated by application", required = true, example = "1123e4567-e89b-12d3-a456-426614174000")
    @XmlTransient
    private UUID invoiceId;

    @ApiModelProperty(value = "Data ksiegowania", required = true, example = "2021-09-30")
    @XmlTransient
    @Column(name = "data")
    private String date;

    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinColumn(name = "invoice_id")
    @XmlElement(name = "komputer")
    private List<Computer> computers;

    @PrePersist
    public void getDateFromComputer() {
        this.date = computers.stream()
                .findAny()
                .map(Computer::getAccountingDate)
                .get()
                .toString();
    }
}
